# Generated by Django 3.0 on 2025-03-09 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('district', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('College_name', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=200)),
                ('point', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('EVENT_COORDINATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_Coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('district', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticket_no', models.BigIntegerField()),
                ('EVENT_DETAILS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_details')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report', models.CharField(max_length=200)),
                ('EVENT_COORDINATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_Coordinator')),
                ('EVENT_DETAILS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_details')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Booking')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('notification', models.CharField(max_length=200)),
                ('EVENT_COORDINATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_Coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feedback', models.CharField(max_length=200)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='event_coordinator',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('certificate', models.CharField(max_length=200)),
                ('EVENT_DETAILS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_details')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='EVENT_DETAILS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_details'),
        ),
        migrations.AddField(
            model_name='booking',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
        migrations.CreateModel(
            name='Activity_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.BigIntegerField()),
                ('EVENT_COORDINATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_Coordinator')),
                ('EVENT_DETAILS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_details')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
    ]
