# Generated by Django 3.0 on 2025-03-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_details',
            name='latitude',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_details',
            name='longitude',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
