# Generated by Django 3.0 on 2025-03-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_point',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Sports', 'Sports'), ('Arts', 'Arts'), ('Volunteering', 'Volunteering'), ('Entrepreneurship', 'Entrepreneurship')], default='Technical', max_length=50),
        ),
        migrations.AddField(
            model_name='activity_point',
            name='level',
            field=models.CharField(choices=[('College', 'College Level'), ('University', 'University Level'), ('National', 'National Level')], default='College', max_length=50),
        ),
        migrations.AddField(
            model_name='activity_point',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='EVENT_COORDINATOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_points', to='myapp.Event_Coordinator'),
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='EVENT_DETAILS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_points', to='myapp.Event_details'),
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_points', to='myapp.Student'),
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='point',
            field=models.PositiveIntegerField(),
        ),
    ]
