# Generated by Django 3.0 on 2025-03-22 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250317_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_point',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='EVENT_COORDINATOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_Coordinator'),
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='EVENT_DETAILS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_details'),
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='level',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activity_point',
            name='point',
            field=models.IntegerField(),
        ),
    ]
