# Generated by Django 3.0 on 2025-03-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250322_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
            ],
        ),
    ]
