# Generated by Django 3.0 on 2025-03-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_point',
            name='category',
        ),
        migrations.RemoveField(
            model_name='activity_point',
            name='level',
        ),
        migrations.RemoveField(
            model_name='activity_point',
            name='point',
        ),
        migrations.AddField(
            model_name='activity_point',
            name='ACTIVITY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Activity'),
            preserve_default=False,
        ),
    ]
