# Generated by Django 3.0 on 2025-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20250322_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_point',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
