# Generated by Django 3.0 on 2025-03-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_activity_point_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='EVENT_COORDINATOR',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_Coordinator'),
            preserve_default=False,
        ),
    ]
