# Generated by Django 3.0 on 2025-03-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_feedback_event_coordinator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
