# Generated by Django 3.0 on 2025-03-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StdActivitypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=250)),
                ('marks', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('ACTIVITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Activity')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
    ]
